[package]
name    = "okx-lob"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "okx-lob"
path = "src/bin/okx-lob.rs"

[[bin]]
name = "okx-delta"
path = "src/bin/okx-delta.rs"

[dependencies]
# async 运行时
tokio   = { version = "1",    features = ["full"] }
# HTTP 客户端
reqwest = { version = "0.12", features = ["stream", "rustls-tls"], default-features = false }
futures = "0.3"
bytes   = "1"
# 序列化
serde      = { version = "1", features = ["derive"] }
serde_json = "1"
zstd = "0.13"
# 日期
chrono = { version = "0.4", features = ["clock", "serde"] }
# 错误处理
anyhow = "1"
# 进度条
indicatif = "0.17"
# 并行
rayon = "1"
# 文件锁
fs2 = "0.4"
# 解压
tar    = "0.4"
flate2 = "1"
# Parquet 输出
arrow   = "53"
parquet = { version = "53", features = ["arrow"] }
# CLI
clap = { version = "4", features = ["derive"] }
# 日志
tracing            = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

[profile.release]
opt-level     = 3
lto           = true
codegen-units = 1
